HW1
Demontego/afina pull request #1
Opened 2019-09-29 17:10 UTC by Demontego

2019-10-05 15:01 UTC, blumix commented on src/storage/SimpleLRU.cpp
> +  while(_current_size-old_node.value.size()+new_value.size()>_max_size)
можно удалить найденный элемент

2019-10-05 15:01 UTC, blumix commented on src/storage/SimpleLRU.cpp
> +  if((key.size()+value.size())>_max_size)
неправильное форматирование

2019-10-05 15:01 UTC, blumix commented on src/storage/SimpleLRU.h
> +		return;
return из деструктора

2019-10-26 15:27 UTC, blumix requested changes

2019-10-26 15:27 UTC, blumix commented on src/network/mt_blocking/ServerImpl.cpp
> +            _join_threads.notify_one();
проснется только один поток

2019-10-26 15:27 UTC, blumix commented on src/network/mt_blocking/ServerImpl.cpp
> +            std::lock_guard<std::mutex> lock(_mutex);
тут может начать выключаться сервер, и ты добавишь в удаленную очередь новый поток

2019-10-26 15:27 UTC, blumix commented on src/network/mt_blocking/ServerImpl.cpp
>      close(_server_socket);
тут сокет закрывается много раз

2019-11-09 15:05 UTC, blumix requested changes

2019-11-09 15:05 UTC, blumix commented on src/concurrency/Executor.cpp
> +                executor->threads.erase(it);
удаление объекта потока, который еще будет что-то делать

2019-11-09 15:05 UTC, blumix commented on src/concurrency/Executor.cpp
> +            if((executor->empty_condition.wait_until(lock,std::chrono::system_clock::now()+executor->_idle_time)==std::cv_status::timeout)&&
каждый раз начинаешь отсчитывать время заново.

2019-11-09 15:39 UTC, blumix requested changes

2019-11-09 15:39 UTC, blumix commented on src/concurrency/Executor.cpp
> +        task();
ты запускаешь таск находясь в критической секции

2019-11-16 16:08 UTC, blumix requested changes

2019-11-16 16:08 UTC, blumix commented on src/concurrency/Executor.cpp
> +                    std::vector<std::thread>::iterator it =
линейный поиск -- это плохо

2019-11-16 16:08 UTC, blumix commented on src/concurrency/Executor.cpp
> +                if (executor->threads.size() > 0) {
если low_watermark == 0 , то сервер не остановится

2019-12-05 14:02 UTC, xphoenix requested changes

2019-12-05 14:02 UTC, xphoenix commented on src/network/st_nonblocking/Connection.cpp
> +    _event.data.ptr = this;
А man почитать???

2019-12-05 14:02 UTC, xphoenix commented on src/network/st_nonblocking/Connection.cpp
> +            while (readed_bytes > 0) {
Так не будет работать

2019-12-07 18:08 UTC, closed without merging